/**
 * Teks invoice. `document` = label di dokumen PDF (bahasa Inggris, mengikuti template brand);
 * sisanya = teks editor untuk tim (bahasa Indonesia).
 */
export const invoiceText = {
  document: {
    title: "Invoice",
    numberPrefix: "#",
    draftNumber: "DRAFT",
    date: "Invoice Date",
    due: "Due Date",
    billTo: "Invoice To",
    totalDue: "Total Due",
    columns: {
      no: "No.",
      description: "Item Description",
      price: "Price",
      qty: "Qty",
      total: "Total",
    },
    subtotal: "Sub Total",
    discount: "Discount",
    tax: (rate: number) => `Tax (${rate}%)`,
    grandTotal: "TOTAL",
    paymentMethod: "Payment Method",
    notes: "Notes",
    thanks: "Thank You For Your Business!",
    paidStamp: "PAID",
    voidStamp: "VOID",
  },

  list: {
    title: "Invoice",
    description: "Buat, cetak, dan pantau pembayaran. Item dan harga bisa diisi bebas.",
    create: "Buat invoice",
    search: "Cari nomor atau nama penerima…",
    empty: "Belum ada invoice. Buat yang pertama; nomornya dibuat otomatis saat disimpan.",
    columns: {
      number: "Nomor",
      billTo: "Ditagihkan ke",
      issueDate: "Tanggal",
      dueDate: "Jatuh tempo",
      total: "Total",
      status: "Status",
    },
    stats: {
      unpaid: "Belum dibayar",
      overdue: "Lewat jatuh tempo",
      paidThisMonth: "Lunas bulan ini",
      invoices: (count: number) => `${count} invoice`,
    },
    overdueBadge: "Lewat jatuh tempo",
  },

  editor: {
    newTitle: "Invoice baru",
    editTitle: (number: string) => `Invoice ${number}`,
    back: "Semua invoice",
    tabs: { form: "Isi invoice", preview: "Pratinjau" },
    sections: {
      billTo: "Ditagihkan kepada",
      items: "Item & harga",
      dates: "Tanggal",
      payment: "Pembayaran",
      signer: "Penanda tangan",
      notes: "Catatan",
    },
    pickClient: "Isi dari daftar klien",
    pickClientNone: "— Tulis manual —",
    fields: {
      name: "Nama penerima",
      company: "Perusahaan / instansi",
      contact: "Email / telepon",
      address: "Alamat",
      description: "Deskripsi jasa",
      descriptionPlaceholder: "Mis. Dokumentasi foto wisuda, 4 jam",
      qty: "Qty",
      price: "Harga satuan",
      lineTotal: "Jumlah",
      discount: "Diskon (Rp)",
      tax: "Tambahkan PPN 11%",
      issueDate: "Tanggal terbit",
      dueDate: "Jatuh tempo",
      paymentMethods: "Metode pembayaran",
      paymentDetails: "Rekening / detail pembayaran",
      signerName: "Nama",
      signerRole: "Jabatan",
      notes: "Catatan untuk klien (opsional)",
    },
    addItem: "Tambah item",
    removeItem: (index: number) => `Hapus item ${index}`,
    itemRemoved: "Item dihapus.",
    undo: "Urungkan",
    save: "Simpan draf",
    saveChanges: "Simpan perubahan",
    saving: "Menyimpan…",
    print: "Cetak / simpan PDF",
    printHint: "Di jendela cetak, pilih “Simpan sebagai PDF”.",
    duplicate: "Duplikat",
    markSent: "Tandai terkirim",
    markPaid: "Tandai lunas",
    void: "Batalkan invoice",
    deleteDraft: "Hapus draf",
    readOnly: {
      paid: (date: string) =>
        `Invoice ini sudah lunas (${date}) dan tidak bisa diubah. Pakai Duplikat untuk membuat invoice serupa.`,
      void: "Invoice ini sudah dibatalkan dan tidak bisa diubah. Nomornya tidak akan dipakai lagi.",
    },
    unsaved: "Ada perubahan yang belum disimpan.",
    confirm: {
      paidTitle: "Tandai invoice ini lunas?",
      paidDescription: "Status berubah menjadi Lunas dan invoice dikunci dari perubahan.",
      paidDate: "Tanggal diterima",
      voidTitle: "Batalkan invoice ini?",
      voidDescription:
        "Invoice dibatalkan permanen. Nomornya tidak akan dipakai lagi, dan tindakan ini tidak bisa diurungkan.",
      deleteTitle: "Hapus draf ini?",
      deleteDescription:
        "Draf dan semua itemnya dihapus permanen. Nomornya tidak dipakai ulang supaya urutan tetap aman.",
    },
    toast: {
      saved: (number: string) => `Draf ${number} tersimpan.`,
      updated: "Perubahan tersimpan.",
      sent: "Ditandai terkirim.",
      paid: "Invoice ditandai lunas.",
      voided: "Invoice dibatalkan.",
      deleted: "Draf dihapus.",
      failed: "Gagal menyimpan. Periksa koneksi lalu coba lagi.",
    },
    errors: {
      name: "Isi nama penerima.",
      items: "Tambahkan minimal satu item dengan deskripsi.",
      dueDate: "Jatuh tempo tidak boleh sebelum tanggal terbit.",
    },
  },

  settings: {
    title: "Pengaturan",
    description: "Data perusahaan ini otomatis dipakai di setiap invoice baru.",
    save: "Simpan pengaturan",
    saved: "Pengaturan tersimpan.",
    fields: {
      companyName: "Nama perusahaan",
      phone: "Telepon",
      email: "Email",
      website: "Website",
      address: "Alamat singkat",
      paymentMethods: "Metode pembayaran bawaan",
      bankDetails: "Rekening bawaan",
      bankDetailsHint: "Mis. BCA 1234567890 a.n. WeaveLens",
      signerName: "Nama penanda tangan bawaan",
      signerRole: "Jabatan penanda tangan bawaan",
    },
  },
};
